spring:
  data:
    mongodb:
      username: diallodev
      password: passer
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090